### ISSUE TITLE
a web-key for "twin-surfing": a friend as a proxy fetching a website // converted links (from web to localhost)

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#23]
Introducing a web-key: Friends fetching a single website URL for storing in / browsing from own URL database

URL 
(e.g. recieved in chat window)  (opt.: -> OpenVPN-Protocol) 
-> Spot-Entry -> ... Echo ... -> Spot-Exit 
(opt.: -> OpenVPN-Protocol) &
->URL insertation to Spot websearch DB & browsing html from websearch DB or as PDF

Ideally, as automatted process for URLs pasted in a chat window: "twin-surfing", resp. "dialogue browsing" or a "converted browse":

Me: URL
You: "Returned: Dialogue Browse" (-> browse localhost URL entry).

Instead of a new web-key, the chat-key can also send it over the url-key, if a "twin-key status" of both meets the settings and the status bar indicates "dialogue browsing" as enabled (both keys present and tied to each other; 

respective: at least one URL-Key is present and any chat-URL-request sends the site to all given URL-Keys 

- hence the concept is simple: any URL pasted in chat is added to the local database of the requester, 

the rest is magic: the URL hash at the requester`s side is fetched from local database and displayed over a swapping chat-link ("converted-link") to be clicked, coming in over the URL-key from the friend).

**Comment by textbrowser** [comment]
Nope. :)

**Comment by textbrowser** [comment]
Google killed Poptastic and therefore Delta Droid. Check!

I have another project where SO publishes entire pages to GitHub. GH hasn't yet terminated the project. It will at some point because those pages will surpass a limit.

Idea is simple. Utilize free Web services for sharing content. Content may be encrypted or not. Poptastic is a simple paradigm for such a process. Dooble has Peekaboo. Create a message, paste it in form, have someone decrypt it. Done.

I know who you are and stop blasting me with silly requests.
