### ISSUE TITLE
Magnet-URI-Links including Neighbors

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/spot-on#35]
Hello,

though the Echo is not tied to IP-addresses and StarBeam Magnets are just channels not tied necessarily to specific files,
the request ist to add/extend Magnet-Links for neighbours in a style like

magnet:?ct=aes256&ek=testkey&ht=blake2b_512&mk=testhash&xt=urn:starbeam

- &ipv4=  (&ipv6=)
- &port=
- &filename=

for the StarBeam / Download Tab (urn:starbeam). 

This makes downloadlinks more sticky to dedicated sources and dedicated files, which can be listed in e.g. a download portal.
Users see, if the IP/neighbor works, that the file is still offered for a download.

Regards & Thanks.

**Comment by textbrowser** [comment]
This is an interesting and difficult request and dilutes the Spot-On because a path is more important than another path. Fragmentation is also dysfunctional with this because a specific path is required and since it is specific, it is only one. One cannot fragment over a single entity. The problem is that a StarBeam is separate of the network details and you're requesting that it become aware of it. It burdens the system with a review of each packet.

**Comment by textbrowser** [comment]
And this is super artificial and superficial unless a device has true multiple networks. Multiple neighbors on a single network do not improve the network. A download will complete faster than two downloads and faster than three downloads.

**Comment by textbrowser** [comment]
I am on Wireless A and connected to two computers. Wireless A is a shared resource regardless of Spot-On. Spot-On will not magically transfer bytes to computer 1 and computer 2 faster because I instruct it to only send data on this channel for this data and that channel for that data. If I flush 10 toilets in a house, that water is shared on one drain. I have to flush them carefully. TCP is my flushy because it does that work for you.

**Comment by textbrowser** [comment]
There is also the problem of a decrepit magnet. If the magnet is invalid and Spot-On must honor it, an invalid neighbor produces an inactive StarBeam. One is then confused and must learn. Correct the behavior by inventing the neighbor which cannot work. Or, even more annoying, correct the StarBeam. A StarBeam works over one or several neighbors. It works. It need not consider complexities. And anyway, multiple Spot-On instances which are local can produce this request.
