### ISSUE TITLE
Web-Search-Interface with Key-Download-Link (Export-Keys-Function on the HTML-webpage).

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/spot-on#39]
Hello,

while the client web-search interface works (next to rss) via f2f with a key-exchange, the webinterface is just "there" to browse.

(Is there a way btw to host the webinterface for the websearch as a hidden server behind Tor?)

However, the request is, to have in the Webinterface for Websearch a link in the top or buttom of the webpage, probably in the bottom page navigation bar, in the right, to downlaod either all keys or the URL-key (as defined by the user, if wanted, otherwise all keys: The user could have in Options the choice for downloading all keys and/or only the URL key.)

The idea is to not only offer search for the instance, but also to download the search database f2f from the webinterface.

Sentence on the webpage:
"Install Spot-On, Download THIS key, connnect to the Echo network or my, THIS IP of the Echo-Server, and download the search Index via f2f over my key."

Offering the download of the key as a link on the websearch webpage follows the "Export Keys" .txt file.

The interesting thing is considering #38 that this key download includes probably the tor-string (rico-tunnel). 
That means even if the websearch is within Tor and shown as a hidden service on an onion webserver, the key-download enables to download the search engines index, the URL.db, over a Tor-Tunnel between two users.

That makes searching the web serverless! And also distributs the URL.db with the download of the keys from the Websearch-Page. That means no other com-channel is needed for the URL-Key-Exchange, if not the internal channels are used or are already established.

If that is an excellenct Web-Search instance, I want the key and download and share the database, hence the key needs to be able to be downloaded on the HTML webpage - as the client offers it also via Menu / Tools / Export-Keys. 

Thanks and Regards.

**Comment by textbrowser** [comment]
IPv4 has a limited number of addresses. IPv6 has more addresses, many more. Tor is not required for the first, because it's easy to test every port on every public address. You cannot hide behind Tor. Whatever is believed, one can discover onions without Tor. We don't need to understand the specifics of Tor, because a server has an address and a port. If it's public, someone will find it. We don't even need to understand Tor-ism encryption if that exists in onions.

So, aside of Tor, you don't need it. SSH tunneling is already documented. Have a public server. SSH-tunnel to it with a private computer. Someone accessing the search is actually accessing your home computer. Zero Tor.

As secure as SSH. And SSH tunnels have depths. Firewalls remain. Easy. Problem? Pay for an IP.

No, you're asking for contrarian ideas. You can't download 3 GiB of data. Indices do not exist in the open world. They exist relative to something else. Cannot download indices. The concept is opaque and silly. I want Google index. Index of what? Of Google links. OK. But you're still accessing Google. I want Google index, all. It works now by index. No.

Everything is solved already without Tor and without downloads. I already provide my entire 3 GiB of data on here. So download it and insert it into your database. Be clever about it.

The rest you mention is just words.

**Comment by Sammysupport** [comment]
- F2F URL download is - next to RSS & GIT -  Spot-On's way to fill the own db.
- no one pays for an IP.
- The request was about key management at public exposed contact websites for users of search-instances: using the web interface as a user does not bring in the data of URLs into the own db. If not a key, then provide an RSS feed icon on the websearch web-interface of Spot-On to download the timeline of new added urls per RSS-Feed aggregated.

**Comment by textbrowser** [comment]
Hiding behind a key or a set of keys is what? You still got the problem of reaching a private computer. You don't address that through Tor because that private computer is now accessible through anything if it is open to Tor.

I be computer and I listen. Someone tells me that I listen for Tor. I still listen and because I listen I get screamed at with anyone.

I be computer and I listen through a tunnel. Aha, someone screaming at me but I am safe in tunnel. If someone screams at me through tunnel, I be like 100% of any service ever made. I need filters at the other end.

You want to get to data. So you invent keys. I say why? Why need keys when the data is public but the computer is private. Why you invert the Sun?

**Comment by Sammysupport** [comment]
as said, it is not about hiding, it is about sharing and key management. why then so many words regarding Tor? 
IPV6 with data retention might be full transparency in 10 years and provide an age of "zero-Tor".
And for sure it is about having a working tunnel without buying an IP.
Keeping website-copies private in the non-inverted sun could probably be needed as websites might be copyrighted too.
