### ISSUE TITLE
Data synchronization over XMPP.

### ISSUE THREAD

**Issue by sjehuda** [textbrowser/spot-on#43]
**Is your feature request related to a problem? Please describe.**
This feature offers synchronization functionality of feeds, entries, read status etc.

**Describe the solution you would like**
Utilize XMPP as a platform for data synchronization.

**Describe alternatives you have considered**
No.

**Additional context**
My name is Schimon, and I am a co-founder of project Blasta.

Blasta is an collaborative annotation management system (i.e. bookmarks manager) which purpose is to make bookmarks accessible from anywhere.

The experiment of Blasta has been successfull and I intend to write an extension a Qt browser in order to realize this integration and possibility.

I advise to stongly consider to utilize the XMPP platform as a system to synchronize browser data, including bookmarks, history, tabs, cookies, password etc.

Chris:
> XMPP?

Schimon:
> Yes. XMPP, the *Extensible* Messaging and Presence Protocol.

Chris:
> This must be a mistake.

Schimon:
> **There is no mistake!**

Please. Watch the video presentation for the technicalities or visit these resources:
- https://blasta.woodpeckersnest.eu/help/about/xmpp/pubsub
- https://blasta.woodpeckersnest.eu/help/about/xmpp/atomsub

|          |                                                    |
|      --- | ---                                                |
| Code     | https://git.xmpp-it.net/sch/Blasta                 |
| Video    | https://video.xmpp-it.net/w/cfozoUeVLFbBFMCCSCJ1Dn |
| Instance | https://blasta.woodpeckersnest.eu                  |
|          |                                                    |

Resources:
- https://portal.mozz.us/gemini/woodpeckersnest.space/~schapps/journal/2024-11-28-xmpp-for-browsers.gmi
- https://github.com/jarun/buku/discussions/795

**Comment by textbrowser** [comment]
What data you want shared?

**Comment by textbrowser** [comment]
Spot-On don't do bookmarks. It do Web pages all of them. And RSS. And anything else like files could be video games or books or songs or whatever is jolly.

**Comment by textbrowser** [comment]
XMPP requires libraries. I don't want maintain libraries. Never ever maintain libraries.

**Comment by sjehuda** [comment]
> What data you want shared?

The data that I want to synchronize would be:
- Feeds
- Entries (i.e. links) and their read and unread status.
- Settings
- And any other data which is stored on the machine locally and not stored on server.

**Comment by sjehuda** [comment]
> XMPP requires libraries. I don't want maintain libraries. Never ever maintain libraries.

The only required functionality is XEP-0060: Publish-Subscribe which is reponsible for managing PubSub nodes.

No other functionality is required (i.e. messaging and presense)

**Comment by sjehuda** [comment]
> Spot-On don't do bookmarks. It do Web pages all of them. And RSS. And anything else like files could be video games or books or songs or whatever is jolly.

The mention of bookmarks was meant to present to you a realization of how synchronization can be implemented over XMPP.

The Blasta project is currently the only example that I have.

**Comment by textbrowser** [comment]
How does Blasta Pasta work without servers? Will Luigi be there? If I need a pasta account, I already die. Spot-On doesn't need accounts. If you want account, it'll be there for Poptastic but that's not necessary to work. XMPP was all about accounts and registrations.

**Comment by sjehuda** [comment]
Yes. XMPP would require an account.

Yje general idea is depicted in these posts:
- https://portal.mozz.us/gemini/woodpeckersnest.space/~schapps/journal/2024-11-28-xmpp-for-browsers.gmi
- ttps://portal.mozz.us/gemini/woodpeckersnest.space/~schapps/journal/2024-12-09-atom-over-xmpp-for-news-readers.gmi

I intend to create a Falkon extension which realizes such synchronization system.

Do you want to close this issue?

**Comment by textbrowser** [comment]
Spot-On is not a browser. :P

**Comment by sjehuda** [comment]
I know.

That post relates to browsers and news readers as one.

**Comment by textbrowser** [comment]
If accounts are required, the concept is already gloomy. Spot-On and Smoke inspire new beliefs. Accounts are replaced through public keys and simple identifiers for discovering loved ones. Such as sjehuda and textbrowser. Signal eliminated (?) the telephone number requirement. Smoke never, ever required telephone numbers. I would like XMPP if I could communicate through Spot-On in its system without a library. The problem with these systems is that they exist within themselves. Do you speak other languages? People do. Not these systems. Spot-On invented the near-real-time communications through electronic mail. How? E-Mail is standard and its requirements are simple. See the numerous communications programs and they all live within themselves. Delta Chat borrowed important concepts from Spot-On.
Anyway, account-less or account-full without libraries.

**Comment by textbrowser** [comment]
And look at the promises of all the coolest chat places. Freedom of this and freedom of that. All promises. Signal is funded by huge tech. whatever it claims otherwise. It has its own sphere of influence and I ain't a quack. Others have recognized that every chat company is here to give YOU what you need. Free and free of charge. It's all ingrained. Can't Signal with any other client. No one gives away free servers to run your own service. I'm singling Signal because it dominates. There is Snap Chat and a myriad of other stupid chat boxes, some open some kind-of-open, and some proprietary. And some are funded by Russians and some by the US. And their scope in their entirety is dominance. None cooperate with anyone or any other service. I can have Smoke sharing files with non-Smoke. I can share Spot and Smoke. Some of the nifty gritty details are difficult because of cryptographic limitations and the mechanisms in which data exist. But it is possible, but they don't want to do it because it means they have to share and think big. They think big in terms of addicts. :)

**Comment by textbrowser** [comment]
The Echo is protocol-less. No protocol. Zero. The Universe has laws restrictions but it doesn't tell you how to talk. It's like, here's this medium and explore it and you decide what 101010110101010101 means to you.

**Comment by sjehuda** [comment]
> If accounts are required, the concept is already gloomy. Spot-On and Smoke inspire new beliefs. Accounts are replaced through public keys and simple identifiers for discovering loved ones.

I understand, yet you can decide on the server that you want to open an account at.

Dead or alive, you can choose the server or establish your server to store the data on.

**Comment by sjehuda** [comment]
> The Echo is protocol-less. No protocol. Zero. The Universe has laws restrictions but it doesn't tell you how to talk. It's like, here's this medium and explore it and you decide what 101010110101010101 means to you.

Please, Explain.

**Comment by textbrowser** [comment]
> > And look at the promises of all the coolest chat places.
> 
> I am well aware of this issue.
> 
> Also, governments gave clandestine agreements with those type of messaging platforms to share information with the government whether legally or otherwise.
> 
> In a case when a messaging services refuses to terms, the government would cennsor it and stop the press from promoting and mentioning it.
> 
> Unlike these imposters, XMPP is independent. You can establish an XMPP server and restrict it to a single or selected hostnames.

The entire business model is entertainment. And some say that the Internet will bring in democracy and liberation of information! And they cheer with applause. The Internet fuels propaganda, stupidity, riots, hate-speech, and paranoia. The  top-ten Web sites in the world according to Wikipedia are related to communications. Only one is about information, Wikipedia. And communications are entertainment. And of those ten, only one is non-profit and is under constant attack because it promotes knowledge. Business thrives on misinformation because misinformation generates mistrust and mistrust generates engagement and engagement generates profit. While the initial belief was that the Internet would promote world-class information, it has promoted world-class stupidity.

**Comment by textbrowser** [comment]
And clever and smart people do not care for XMPP nor Signal nor any other popular solution. The solutions already exist regardless of their difficulties. Spot-On exists because of curiosity and curiosity sometimes inspire other discoveries which can be unrelated to the initial goal.

**Comment by textbrowser** [comment]
There is the Echo and there is Spot-On which exists in the Echo. The Echo doesn't exist in Spot-On. Wireless communications are possible because of electromagnetic radiation. Radio, wireless, television, microwaves all exist because of radiation. Radiation doesn't exist because of them.

**Comment by sjehuda** [comment]
> > > And look at the promises of all the coolest chat places.
> > 
> > 
> > I am well aware of this issue.
> > Also, governments gave clandestine agreements with those type of messaging platforms to share information with the government whether legally or otherwise.
> > In a case when a messaging services refuses to terms, the government would cennsor it and stop the press from promoting and mentioning it.
> > Unlike these imposters, XMPP is independent. You can establish an XMPP server and restrict it to a single or selected hostnames.
> 
> The entire business model is entertainment. And some say that the Internet will bring in democracy and liberation of information! And they cheer with applause. The Internet fuels propaganda, stupidity, riots, hate-speech, and paranoia. The top-ten Web sites in the world according to Wikipedia are related to communications. Only one is about information, Wikipedia. And communications are entertainment. And of those ten, only one is non-profit and is under constant attack because it promotes knowledge. Business thrives on misinformation because misinformation generates mistrust and mistrust generates engagement and engagement generates profit. While the initial belief was that the Internet would promote world-class information, it has promoted world-class stupidity.

I am not sure of the factuality of the information.

I suppose, that the list of the alleged top ten site is meant for use to internalize and to believe that it is true, in order to believe that promoting other type of resources would be futile.

I do not visit not use those alleged top ten sites. I visit other sites and I utilize other type of resources, especially BitTorrent and most recently Gemini as well.

**Comment by sjehuda** [comment]
> And clever and smart people do not care for XMPP nor Signal nor any other popular solution.

I am a Jew and I was involved with Jewish communities for years.

The solution that Jews do is to organize a boycott.

While I do not intend to organize a boycott, I boycott by my own.

That is, I am available via Email, IRC and XMPP.

> The solutions already exist regardless of their difficulties. Spot-On exists because of curiosity and curiosity sometimes inspires other discoveries which can be unrelated to the initial goal.

The only benefit in signing up to some centralized platforms is to study those platforms.

**Comment by sjehuda** [comment]
> There is the Echo and there is Spot-On which exists in the Echo. The Echo doesn't exist in Spot-On. Wireless communications are possible because of electromagnetic radiation. Radio, wireless, television, microwaves all exist because of radiation. Radiation doesn't exist because of them.

I have read this comment several times. I am not sure that I understood it.

Please. Elaborate.

**Comment by textbrowser** [comment]
![top](https://github.com/user-attachments/assets/883b1ec4-77fb-4188-8aca-a276802e1b88)

**Comment by textbrowser** [comment]
Social media and news. One search and one encyclopedia. YT is special because it provides education. However, one must investigate the popular casts on it to determine if they're educational or yet another lively propaganda channels.

**Comment by sjehuda** [comment]
I agree.

**Comment by textbrowser** [comment]
That is the Internet. And others have applied rigorous research standards regarding it. It may have been an aspiring concept in the initial steps, however, like most human endeavors, it's monetized for profit.

**Comment by textbrowser** [comment]
https://www.infegy.com/blog/how-companies-monetized-the-internet-and-social-media

**Comment by textbrowser** [comment]
I approach my little communications projects as can-I-do-this. And then apply challenges to myself to do things I cannot do with other projects or do not find interesting to investigate. Self doubt into discovery. Is interesting. I know communications can be private, secure, and protocol-less. But they won't be because every projects needs to survive if that project has financial people. And they survive by spreading their protocols and preventing others from existing. It's simple economics and human behavior. Spot-On, again, has protocols but the Echo is protocol-less. You could have a Spot-On server echo data for multiple projects if those projects were open; open in their ability to process their information without rigid protocols. And Spot-On can do that. It's selective. Like a carnival. You know, you have a case of toys and you want a specific toy with the little claw.

**Comment by sjehuda** [comment]
I think that I understand.

Thank you for posting the link to that article.

**Comment by textbrowser** [comment]
> > > > And look at the promises of all the coolest chat places.
> > > 
> > > 
> > > I am well aware of this issue.
> > > Also, governments gave clandestine agreements with those type of messaging platforms to share information with the government whether legally or otherwise.
> > > In a case when a messaging services refuses to terms, the government would cennsor it and stop the press from promoting and mentioning it.
> > > Unlike these imposters, XMPP is independent. You can establish an XMPP server and restrict it to a single or selected hostnames.
> > 
> > 
> > The entire business model is entertainment. And some say that the Internet will bring in democracy and liberation of information! And they cheer with applause. The Internet fuels propaganda, stupidity, riots, hate-speech, and paranoia. The top-ten Web sites in the world according to Wikipedia are related to communications. Only one is about information, Wikipedia. And communications are entertainment. And of those ten, only one is non-profit and is under constant attack because it promotes knowledge. Business thrives on misinformation because misinformation generates mistrust and mistrust generates engagement and engagement generates profit. While the initial belief was that the Internet would promote world-class information, it has promoted world-class stupidity.
> 
> I am not sure of the factuality of the information.
> 
> I suppose, that the list of the alleged top ten site is meant for use to internalize and to believe that it is true, in order to believe that promoting other type of resources would be futile.
> 
> I do not visit not use those alleged top ten sites. I visit other sites and I utilize other type of resources, especially BitTorrent and most recently Gemini as well.

The representatives of US democracy are not interested in the people they represent. They are interested in profit and profit arrives from Face, from Google, and from every popular site. Signal exists to create connections and data. It's not important if it's private or anonymous. It generates traffic for AWS. More traffic, more business for Amazon. It's a great funneling of taxes into Amazon, Google, and whatever company. So privacy is irrelevant. None of these gadgets are necessary. E-Mail exists and provides privacy. It doesn't provide anonymity and it could be made to do so. But it won't be because e-mail is ancient. And PGP and GPG have been insulted into irrelevancy instead of being improved and Spot-On includes a model into such an improvement, indirectly.

**Comment by textbrowser** [comment]
https://signal.org/blog/signal-is-expensive/

**Comment by textbrowser** [comment]
AWS, Google, MS. So whatever the source of money into Signal some of that nice cash goes into three monopolies. Some donations, some taxes, some whatever. They money isn't going into small business even if small business could host it. It's a grand-old funnel machine. And you and I are paying for it.

**Comment by textbrowser** [comment]
Meow meow meow. But at least it's open source or something. And we ain't picking on Signal. That one example. Big ones are all funded weirdly and suspiciously. And they got their open forums on who and where and why money come in. And people are like wow, that has the money to be reviewed by others who work at universities and these universities receive public money or other super-genius level research centers with little pencils and pens for penetration testing and super cryptographers. Anyway, super fun. Super fun stuff for people outside of common society.

**Comment by textbrowser** [comment]
The cuteness is that it don't have to be factual because is difficult to prove and wacky too. Like we think we bonkers for talking about big business but it is, right? Like how can the Internet be big entertainment? But it is. Big business, not about information and knowledge but information on little common people and then big common people and what they do and say. Small people on what they buy and big people on what they do with the data of little people. And maybe some wink-and-dink on big people because some of them are nasty perverts so. Super fun.

**Comment by sjehuda** [comment]
I think, that this article may be of interest to you
https://www.process-one.net/blog/breaking-down-the-costs-of-large-messaging-services/

**Comment by textbrowser** [comment]
How about data synchronization over GIT? It's now alive. You may share texts through a GIT server. Spot-On texts and GPG texts. And there are many GIT servers beyond this one. In places where speech is not owned by the technofeudalism class.

**Comment by sjehuda** [comment]
It sounds good.

As with XMPP it would also require an account (i.e. a repository of
choice of an account) git://git.i2p/account/repository.

Given the arbitrary limitations of XMPP PubSub nodes (ejabberd is the
only one that provides the best infrastructure without limitations),
utilizing Git is probably a better idea.

**Comment by textbrowser** [comment]
Probably? Is a splendid.

https://european-alternatives.eu/alternative-to/github

Accounts? Nope! Git servers allow open repositories. So you can share the account and a token or multiple tokens with comrades. Those comrades are then allowed to write only to that repository. And they don't need accounts. You need to trust them. I think you can restrict, additionally, things by IP on git.

https://docs.github.com/en/enterprise-cloud@latest/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-organization

Of course you don't need GH for that if you have a private server.

**Comment by textbrowser** [comment]
Look for Prison Blues in Spot. It's in Chat and in Rosetta. In Rosetta, GPG is there. So you may craft GPG messages and paste them in e-mail or elsewhere or you can text with GPG in real-time through git. In Chat, git and Echo. And in git, SMP works. Is a wonderful curiosity.

**Comment by textbrowser** [comment]
SMP = Silly Millionaire Protocol = Zero-proof Credentials

The SMP is a curious thing because it works within the package of a message. Like sending an e-mail to someone, encrypted, and the first message is step 1. Etc., etc., etc. And Spot-On is asynchronous. Or is that Smoke. I think one of them assembles the order. Smoke will work with git too, someday. Free servers until.
